export const mockFiles = [
  {
    name: 'Document1.pdf',
    size: 102400,
    type: 'PDF',
    lastModified: new Date().getTime(),
    shared: 'No',
  },
  {
    name: 'ProjectFolder',
    size: 204800000,
    type: 'Folder',
    lastModified: new Date().getTime(),
    shared: 'Yes',
  },
  {
    name: 'Presentation.pptx',
    size: 512000,
    type: 'pptx',
    lastModified: new Date().getTime(),
    shared: 'No',
  },
  {
    name: 'Spreadsheet.xlsx',
    size: 256000,
    type: 'xlsx',
    lastModified: new Date().getTime(),
    shared: 'Yes',
  },
  {
    name: 'TextFile.txt',
    size: 1024,
    type: 'txt',
    lastModified: new Date().getTime(),
    shared: 'No',
  },
  {
    name: 'DocsGame',
    size: 260200000,
    type: 'Folder',
    lastModified: new Date().getTime(),
    shared: 'No',
  },
  {
    name: 'CodeGames',
    size: 2300000000,
    type: 'Folder',
    lastModified: new Date().getTime(),
    shared: 'No',
  },
  {
    name: 'Docs',
    size: 10000000,
    type: 'Folder',
    lastModified: new Date().getTime(),
    shared: 'No',
  },
  {
    name: 'Docs',
    size: 10000000,
    type: 'Folder',
    lastModified: new Date().getTime(),
    shared: 'No',
  },
  {
    name: 'Spreadsheet.xlsx',
    size: 256000,
    type: 'xlsx',
    lastModified: new Date().getTime(),
    shared: 'Yes',
  },
  {
    name: 'Image1.png',
    size: 204800,
    type: 'PNG',
    lastModified: new Date().getTime(),
    shared: 'Yes',
  },
];